# Generated by Django 2.2 on 2019-11-26 18:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('Entity_Type', models.CharField(default='', max_length=100)),
                ('Entity_Name', models.CharField(default='', max_length=100)),
                ('Entity_Regex', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=250)),
                ('answer', models.CharField(default='', max_length=400)),
                ('audio', models.CharField(default='', max_length=100)),
                ('video', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=100)),
                ('doc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntentToTask',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('Intent_Name', models.CharField(default='', max_length=100)),
                ('Task_Name', models.CharField(default='', max_length=100)),
                ('Action_Url', models.CharField(default='', max_length=100)),
                ('post_action', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recommunded_data',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('entity_id', models.CharField(default='', max_length=100)),
                ('task_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('task', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('utterance', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultMap',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('taskId', models.IntegerField(default=0)),
                ('entityId', models.IntegerField(default=0)),
                ('keyof', models.CharField(default='', max_length=100)),
                ('redirectTo', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskToEntity',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('Task_Id', models.IntegerField(default=0)),
                ('Entity_Id', models.IntegerField(default=0)),
                ('Entity_Name', models.CharField(default='', max_length=100)),
                ('Entity_Question', models.CharField(default='', max_length=250)),
                ('Entity_alternet_qustion', djongo.models.fields.ListField(default='', max_length=300)),
                ('Entity_Sequence', models.IntegerField(default=0)),
                ('task_redirect', models.CharField(default='', max_length=100)),
                ('pre_text', models.CharField(default='', max_length=100)),
                ('pre_action_url', models.CharField(default='', max_length=100)),
                ('interview_url', models.CharField(default='', max_length=100)),
                ('value_collection_name', models.CharField(default='', max_length=100)),
                ('collection_url', models.CharField(default='', max_length=100)),
                ('validation_url', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
