# Generated by Django 2.2 on 2019-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('request_data', models.CharField(default='', max_length=300)),
                ('responce_data', models.CharField(default='', max_length=500)),
                ('request_user', models.CharField(default='', max_length=50)),
                ('responce_user', models.CharField(default='', max_length=50)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
