# Generated by Django 2.2 on 2019-12-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='task_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='task_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
