# Generated by Django 2.2 on 2019-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191210_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
