# Generated by Django 2.2 on 2020-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200125_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
