# Generated by Django 2.0 on 2020-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_faq_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='nodes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='faq',
            name='user_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
