# Generated by Django 2.0 on 2020-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_nodesmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesmodule',
            name='parental_node_level',
            field=models.IntegerField(default=0),
        ),
    ]
