# Generated by Django 2.0 on 2020-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200219_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesmodule',
            name='node_value',
            field=models.CharField(default='', max_length=70),
        ),
    ]
