# Generated by Django 2.0 on 2020-02-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_nodesmodule_node_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesmodule',
            name='parental_node',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
