# Generated by Django 2.0 on 2020-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200219_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodesmodule',
            old_name='parental_node',
            new_name='parental_node_name',
        ),
        migrations.AddField(
            model_name='nodesmodule',
            name='parental_node_value',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
