# Generated by Django 2.0 on 2020-02-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200219_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(default='', max_length=70)),
                ('node_value', models.CharField(default='', max_length=70)),
                ('node_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='nodesmodule',
            name='parental_node_level',
        ),
        migrations.RemoveField(
            model_name='nodesmodule',
            name='parental_node_name',
        ),
        migrations.RemoveField(
            model_name='nodesmodule',
            name='parental_node_value',
        ),
        migrations.AddField(
            model_name='nodesmodule',
            name='parental_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ParentalNode'),
        ),
    ]
