# Generated by Django 2.0 on 2020-02-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200219_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesmodule',
            name='parental_node',
        ),
        migrations.AddField(
            model_name='nodesmodule',
            name='parental_node_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ParentalNode',
        ),
    ]
